insert into public.catalogue_phone_models (
  code,
  brand,
  name,
  sort_order,
  is_active
)
values
  ('iphone-16', 'Apple', 'iPhone 16', 10, true),
  ('iphone-16-plus', 'Apple', 'iPhone 16+', 20, true),
  ('iphone-16-pro', 'Apple', 'iPhone 16 Pro', 30, true),
  ('iphone-16-pro-max', 'Apple', 'iPhone 16 Pro Max', 40, true),
  ('iphone-15', 'Apple', 'iPhone 15', 50, true),
  ('iphone-15-plus', 'Apple', 'iPhone 15+', 60, true),
  ('iphone-15-pro', 'Apple', 'iPhone 15 Pro', 70, true),
  ('iphone-15-pro-max', 'Apple', 'iPhone 15 Pro Max', 80, true),
  ('iphone-14', 'Apple', 'iPhone 14', 90, true),
  ('iphone-14-plus', 'Apple', 'iPhone 14+', 100, true),
  ('iphone-14-pro', 'Apple', 'iPhone 14 Pro', 110, true),
  ('iphone-14-pro-max', 'Apple', 'iPhone 14 Pro Max', 120, true),
  ('iphone-13', 'Apple', 'iPhone 13', 130, true),
  ('iphone-13-mini', 'Apple', 'iPhone 13 Mini', 140, true),
  ('iphone-13-pro', 'Apple', 'iPhone 13 Pro', 150, true),
  ('iphone-13-pro-max', 'Apple', 'iPhone 13 Pro Max', 160, true),
  ('iphone-12', 'Apple', 'iPhone 12', 170, true),
  ('iphone-12-mini', 'Apple', 'iPhone 12 Mini', 180, true),
  ('iphone-12-pro', 'Apple', 'iPhone 12 Pro', 190, true),
  ('iphone-12-pro-max', 'Apple', 'iPhone 12 Pro Max', 200, true),
  ('iphone-11', 'Apple', 'iPhone 11', 210, true),
  ('iphone-11-pro', 'Apple', 'iPhone 11 Pro', 220, true),
  ('iphone-11-pro-max', 'Apple', 'iPhone 11 Pro Max', 230, true),
  ('iphone-xs-max', 'Apple', 'iPhone XS Max', 240, true),
  ('iphone-xr', 'Apple', 'iPhone XR', 250, true),
  ('iphone-x-xs', 'Apple', 'iPhone X/XS', 260, true),
  ('iphone-7', 'Apple', 'iPhone 7', 270, true),
  ('iphone-7-plus', 'Apple', 'iPhone 7+', 280, true),
  ('samsung-galaxy-s25', 'Samsung', 'Samsung Galaxy S25', 290, true),
  ('samsung-galaxy-s25-plus', 'Samsung', 'Samsung Galaxy S25+', 300, true),
  ('samsung-galaxy-s25-ultra', 'Samsung', 'Samsung Galaxy S25 Ultra', 310, true),
  ('samsung-galaxy-s24', 'Samsung', 'Samsung Galaxy S24', 320, true),
  ('samsung-galaxy-s24-plus', 'Samsung', 'Samsung Galaxy S24+', 330, true),
  ('samsung-galaxy-s24-ultra', 'Samsung', 'Samsung Galaxy S24 Ultra', 340, true),
  ('samsung-galaxy-s23', 'Samsung', 'Samsung Galaxy S23', 350, true),
  ('samsung-galaxy-s23-plus', 'Samsung', 'Samsung Galaxy S23+', 360, true),
  ('samsung-galaxy-s23-ultra', 'Samsung', 'Samsung Galaxy S23 Ultra', 370, true),
  ('samsung-galaxy-s22', 'Samsung', 'Samsung Galaxy S22', 380, true),
  ('samsung-galaxy-s22-plus', 'Samsung', 'Samsung Galaxy S22+', 390, true),
  ('samsung-galaxy-s22-ultra', 'Samsung', 'Samsung Galaxy S22 Ultra', 400, true),
  ('samsung-galaxy-s21', 'Samsung', 'Samsung Galaxy S21', 410, true),
  ('samsung-galaxy-s21-ultra', 'Samsung', 'Samsung Galaxy S21 Ultra', 420, true),
  ('samsung-galaxy-s20-fe', 'Samsung', 'Samsung Galaxy S20 FE', 430, true),
  ('samsung-galaxy-s21-fe', 'Samsung', 'Samsung Galaxy S21 FE', 440, true),
  ('samsung-galaxy-s23-fe', 'Samsung', 'Samsung Galaxy S23 FE', 450, true),
  ('samsung-galaxy-s24-fe', 'Samsung', 'Samsung Galaxy S24 FE', 460, true),
  ('samsung-galaxy-s8', 'Samsung', 'Samsung Galaxy S8', 470, true),
  ('samsung-galaxy-s9', 'Samsung', 'Samsung Galaxy S9', 480, true),
  ('samsung-galaxy-s10', 'Samsung', 'Samsung Galaxy S10', 490, true),
  ('samsung-galaxy-s20', 'Samsung', 'Samsung Galaxy S20', 500, true),
  ('samsung-galaxy-a02s', 'Samsung', 'Samsung Galaxy A02s', 510, true),
  ('samsung-galaxy-a03', 'Samsung', 'Samsung Galaxy A03', 520, true),
  ('samsung-galaxy-a04', 'Samsung', 'Samsung Galaxy A04', 530, true),
  ('samsung-galaxy-a04e', 'Samsung', 'Samsung Galaxy A04E', 540, true),
  ('samsung-galaxy-a04s', 'Samsung', 'Samsung Galaxy A04S', 550, true),
  ('samsung-galaxy-a06', 'Samsung', 'Samsung Galaxy A06', 560, true),
  ('samsung-galaxy-a12', 'Samsung', 'Samsung Galaxy A12', 570, true),
  ('samsung-galaxy-a13-4g', 'Samsung', 'Samsung Galaxy A13 4G', 580, true),
  ('samsung-galaxy-a13-5g', 'Samsung', 'Samsung Galaxy A13 5G', 590, true),
  ('samsung-galaxy-a14', 'Samsung', 'Samsung Galaxy A14', 600, true),
  ('samsung-galaxy-a15', 'Samsung', 'Samsung Galaxy A15', 610, true),
  ('samsung-galaxy-a16', 'Samsung', 'Samsung Galaxy A16', 620, true),
  ('samsung-galaxy-a22', 'Samsung', 'Samsung Galaxy A22', 630, true),
  ('samsung-galaxy-a23', 'Samsung', 'Samsung Galaxy A23', 640, true),
  ('samsung-galaxy-a24', 'Samsung', 'Samsung Galaxy A24', 650, true),
  ('samsung-galaxy-a25', 'Samsung', 'Samsung Galaxy A25', 660, true),
  ('samsung-galaxy-a32-4g', 'Samsung', 'Samsung Galaxy A32 4G', 670, true),
  ('samsung-galaxy-a32-5g', 'Samsung', 'Samsung Galaxy A32 5G', 680, true),
  ('samsung-galaxy-a33', 'Samsung', 'Samsung Galaxy A33', 690, true),
  ('samsung-galaxy-a34', 'Samsung', 'Samsung Galaxy A34', 700, true),
  ('samsung-galaxy-a35', 'Samsung', 'Samsung Galaxy A35', 710, true),
  ('samsung-galaxy-a53', 'Samsung', 'Samsung Galaxy A53', 720, true),
  ('samsung-galaxy-a54', 'Samsung', 'Samsung Galaxy A54', 730, true),
  ('samsung-galaxy-a55', 'Samsung', 'Samsung Galaxy A55', 740, true),
  ('samsung-galaxy-a72', 'Samsung', 'Samsung Galaxy A72', 750, true),
  ('samsung-galaxy-a73', 'Samsung', 'Samsung Galaxy A73', 760, true),
  ('xiaomi-redmi-8', 'Xiaomi', 'Xiaomi Redmi 8', 770, true),
  ('xiaomi-redmi-note-10-pro', 'Xiaomi', 'Xiaomi Redmi Note 10 Pro', 780, true),
  ('xiaomi-redmi-note-11-pro', 'Xiaomi', 'Xiaomi Redmi Note 11 Pro', 790, true),
  ('xiaomi-redmi-12-pro', 'Xiaomi', 'Xiaomi Redmi 12 Pro', 800, true),
  ('xiaomi-redmi-note-12-4g', 'Xiaomi', 'Xiaomi Redmi Note 12 4G', 810, true),
  ('xiaomi-redmi-note-12-5g', 'Xiaomi', 'Xiaomi Redmi Note 12 5G', 820, true),
  ('xiaomi-redmi-note-12s-4g', 'Xiaomi', 'Xiaomi Redmi Note 12S 4G', 830, true),
  ('xiaomi-redmi-note-12s-5g', 'Xiaomi', 'Xiaomi Redmi Note 12S 5G', 840, true),
  ('xiaomi-redmi-note-13-4g', 'Xiaomi', 'Xiaomi Redmi Note 13 4G', 850, true),
  ('xiaomi-redmi-note-13-pro-4g', 'Xiaomi', 'Xiaomi Redmi Note 13 Pro 4G', 860, true),
  ('xiaomi-redmi-note-13-pro-plus', 'Xiaomi', 'Xiaomi Redmi Note 13 Pro+', 870, true),
  ('xiaomi-poco-m6-pro', 'Xiaomi', 'Xiaomi Poco M6 Pro', 880, true)
on conflict (code) do update
set
  brand = excluded.brand,
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
